export const bigDataObject = {
  bigData: [
    {
      page: 1,
      per_page: 6,
      total: 48,
      total_pages: 8,
      data: [
        {
          id: 1,
          email: 'george.bluth@reqres.in',
          first_name: 'George',
          last_name: 'Bluth',
          avatar: 'https://reqres.in/img/faces/1-image.jpg',
        },
        {
          id: 2,
          email: 'janet.weaver@reqres.in',
          first_name: 'Janet',
          last_name: 'Weaver',
          avatar: 'https://reqres.in/img/faces/2-image.jpg',
        },
        {
          id: 3,
          email: 'emma.wong@reqres.in',
          first_name: 'Emma',
          last_name: 'Wong',
          avatar: 'https://reqres.in/img/faces/3-image.jpg',
        },
        {
          id: 4,
          email: 'eve.holt@reqres.in',
          first_name: 'Eve',
          last_name: 'Holt',
          avatar: 'https://reqres.in/img/faces/4-image.jpg',
        },
        {
          id: 5,
          email: 'charles.morris@reqres.in',
          first_name: 'Charles',
          last_name: 'Morris',
          avatar: 'https://reqres.in/img/faces/5-image.jpg',
        },
        {
          id: 6,
          email: 'tracey.ramos@reqres.in',
          first_name: 'Tracey',
          last_name: 'Ramos',
          avatar: 'https://reqres.in/img/faces/6-image.jpg',
        },
      ],
    },
    {
      page: 2,
      total: 48,
      total_pages: 8,
      data: [
        {
          id: 7,
          email: 'michael.lawson@reqres.in',
          first_name: 'Michael',
          last_name: 'Lawson',
          avatar: 'https://reqres.in/img/faces/7-image.jpg',
        },
        {
          id: 8,
          email: 'lindsay.ferguson@reqres.in',
          first_name: 'Lindsay',
          last_name: 'Ferguson',
          avatar: 'https://reqres.in/img/faces/8-image.jpg',
        },
        {
          id: 9,
          email: 'tobias.funke@reqres.in',
          first_name: 'Tobias',
          last_name: 'Funke',
          avatar: 'https://reqres.in/img/faces/9-image.jpg',
        },
        {
          id: 10,
          email: 'byron.fields@reqres.in',
          first_name: 'Byron',
          last_name: 'Fields',
          avatar: 'https://reqres.in/img/faces/10-image.jpg',
        },
        {
          id: 11,
          email: 'george.edwards@reqres.in',
          first_name: 'George',
          last_name: 'Edwards',
          avatar: 'https://reqres.in/img/faces/11-image.jpg',
        },
        {
          id: 12,
          email: 'rachel.howell@reqres.in',
          first_name: 'Rachel',
          last_name: 'Howell',
          avatar: 'https://reqres.in/img/faces/12-image.jpg',
        },
      ],
    },
    {
      page: 3,
      total: 48,
      total_pages: 8,
      data: [
        {
          id: 13,
          email: 'michael.lawson@reqres.in',
          first_name: 'Michael',
          last_name: 'Lawson',
          avatar: 'https://reqres.in/img/faces/7-image.jpg',
        },
        {
          id: 14,
          email: 'lindsay.ferguson@reqres.in',
          first_name: 'Lindsay',
          last_name: 'Ferguson',
          avatar: 'https://reqres.in/img/faces/8-image.jpg',
        },
        {
          id: 15,
          email: 'tobias.funke@reqres.in',
          first_name: 'Tobias',
          last_name: 'Funke',
          avatar: 'https://reqres.in/img/faces/9-image.jpg',
        },
        {
          id: 16,
          email: 'byron.fields@reqres.in',
          first_name: 'Byron',
          last_name: 'Fields',
          avatar: 'https://reqres.in/img/faces/10-image.jpg',
        },
        {
          id: 17,
          email: 'george.edwards@reqres.in',
          first_name: 'George',
          last_name: 'Edwards',
          avatar: 'https://reqres.in/img/faces/11-image.jpg',
        },
        {
          id: 18,
          email: 'rachel.howell@reqres.in',
          first_name: 'Rachel',
          last_name: 'Howell',
          avatar: 'https://reqres.in/img/faces/12-image.jpg',
        },
      ],
    },
    {
      page: 4,
      total: 48,
      total_pages: 8,
      data: [
        {
          id: 19,
          email: 'michael.lawson@reqres.in',
          first_name: 'Michael',
          last_name: 'Lawson',
          avatar: 'https://reqres.in/img/faces/7-image.jpg',
        },
        {
          id: 20,
          email: 'lindsay.ferguson@reqres.in',
          first_name: 'Lindsay',
          last_name: 'Ferguson',
          avatar: 'https://reqres.in/img/faces/8-image.jpg',
        },
        {
          id: 21,
          email: 'tobias.funke@reqres.in',
          first_name: 'Tobias',
          last_name: 'Funke',
          avatar: 'https://reqres.in/img/faces/9-image.jpg',
        },
        {
          id: 22,
          email: 'byron.fields@reqres.in',
          first_name: 'Byron',
          last_name: 'Fields',
          avatar: 'https://reqres.in/img/faces/10-image.jpg',
        },
        {
          id: 23,
          email: 'george.edwards@reqres.in',
          first_name: 'George',
          last_name: 'Edwards',
          avatar: 'https://reqres.in/img/faces/11-image.jpg',
        },
        {
          id: 24,
          email: 'rachel.howell@reqres.in',
          first_name: 'Rachel',
          last_name: 'Howell',
          avatar: 'https://reqres.in/img/faces/12-image.jpg',
        },
      ],
    },
    {
      page: 5,
      total: 48,
      total_pages: 8,
      data: [
        {
          id: 25,
          email: 'michael.lawson@reqres.in',
          first_name: 'Michael',
          last_name: 'Lawson',
          avatar: 'https://reqres.in/img/faces/7-image.jpg',
        },
        {
          id: 26,
          email: 'lindsay.ferguson@reqres.in',
          first_name: 'Lindsay',
          last_name: 'Ferguson',
          avatar: 'https://reqres.in/img/faces/8-image.jpg',
        },
        {
          id: 27,
          email: 'tobias.funke@reqres.in',
          first_name: 'Tobias',
          last_name: 'Funke',
          avatar: 'https://reqres.in/img/faces/9-image.jpg',
        },
        {
          id: 28,
          email: 'byron.fields@reqres.in',
          first_name: 'Byron',
          last_name: 'Fields',
          avatar: 'https://reqres.in/img/faces/10-image.jpg',
        },
        {
          id: 29,
          email: 'george.edwards@reqres.in',
          first_name: 'George',
          last_name: 'Edwards',
          avatar: 'https://reqres.in/img/faces/11-image.jpg',
        },
        {
          id: 30,
          email: 'rachel.howell@reqres.in',
          first_name: 'Rachel',
          last_name: 'Howell',
          avatar: 'https://reqres.in/img/faces/12-image.jpg',
        },
      ],
    },
    {
      page: 6,
      total: 48,
      total_pages: 8,
      data: [
        {
          id: 31,
          email: 'michael.lawson@reqres.in',
          first_name: 'Michael',
          last_name: 'Lawson',
          avatar: 'https://reqres.in/img/faces/7-image.jpg',
        },
        {
          id: 32,
          email: 'lindsay.ferguson@reqres.in',
          first_name: 'Lindsay',
          last_name: 'Ferguson',
          avatar: 'https://reqres.in/img/faces/8-image.jpg',
        },
        {
          id: 33,
          email: 'tobias.funke@reqres.in',
          first_name: 'Tobias',
          last_name: 'Funke',
          avatar: 'https://reqres.in/img/faces/9-image.jpg',
        },
        {
          id: 34,
          email: 'byron.fields@reqres.in',
          first_name: 'Byron',
          last_name: 'Fields',
          avatar: 'https://reqres.in/img/faces/10-image.jpg',
        },
        {
          id: 35,
          email: 'george.edwards@reqres.in',
          first_name: 'George',
          last_name: 'Edwards',
          avatar: 'https://reqres.in/img/faces/11-image.jpg',
        },
        {
          id: 36,
          email: 'rachel.howell@reqres.in',
          first_name: 'Rachel',
          last_name: 'Howell',
          avatar: 'https://reqres.in/img/faces/12-image.jpg',
        },
      ],
    },
    {
      page: 7,
      total: 48,
      total_pages: 8,
      data: [
        {
          id: 37,
          email: 'michael.lawson@reqres.in',
          first_name: 'Michael',
          last_name: 'Lawson',
          avatar: 'https://reqres.in/img/faces/7-image.jpg',
        },
        {
          id: 38,
          email: 'lindsay.ferguson@reqres.in',
          first_name: 'Lindsay',
          last_name: 'Ferguson',
          avatar: 'https://reqres.in/img/faces/8-image.jpg',
        },
        {
          id: 39,
          email: 'tobias.funke@reqres.in',
          first_name: 'Tobias',
          last_name: 'Funke',
          avatar: 'https://reqres.in/img/faces/9-image.jpg',
        },
        {
          id: 40,
          email: 'byron.fields@reqres.in',
          first_name: 'Byron',
          last_name: 'Fields',
          avatar: 'https://reqres.in/img/faces/10-image.jpg',
        },
        {
          id: 41,
          email: 'george.edwards@reqres.in',
          first_name: 'George',
          last_name: 'Edwards',
          avatar: 'https://reqres.in/img/faces/11-image.jpg',
        },
        {
          id: 42,
          email: 'rachel.howell@reqres.in',
          first_name: 'Rachel',
          last_name: 'Howell',
          avatar: 'https://reqres.in/img/faces/12-image.jpg',
        },
      ],
    },
    {
      page: 8,
      total: 48,
      total_pages: 8,
      data: [
        {
          id: 43,
          email: 'michael.lawson@reqres.in',
          first_name: 'Michael',
          last_name: 'Lawson',
          avatar: 'https://reqres.in/img/faces/7-image.jpg',
        },
        {
          id: 44,
          email: 'lindsay.ferguson@reqres.in',
          first_name: 'Lindsay',
          last_name: 'Ferguson',
          avatar: 'https://reqres.in/img/faces/8-image.jpg',
        },
        {
          id: 45,
          email: 'tobias.funke@reqres.in',
          first_name: 'Tobias',
          last_name: 'Funke',
          avatar: 'https://reqres.in/img/faces/9-image.jpg',
        },
        {
          id: 46,
          email: 'byron.fields@reqres.in',
          first_name: 'Byron',
          last_name: 'Fields',
          avatar: 'https://reqres.in/img/faces/10-image.jpg',
        },
        {
          id: 47,
          email: 'george.edwards@reqres.in',
          first_name: 'George',
          last_name: 'Edwards',
          avatar: 'https://reqres.in/img/faces/11-image.jpg',
        },
        {
          id: 48,
          email: 'rachel.howell@reqres.in',
          first_name: 'Rachel',
          last_name: 'Howell',
          avatar: 'https://reqres.in/img/faces/12-image.jpg',
        },
      ],
    },
  ],
};
